export const UPDATE_NFT_LIST = "UPDATE_NFT_LIST";
export const LOADING = "LOADING";
export const TRANSFERABLETOKEN = "TRANSFERABLETOKEN";
export const UPDATE_SELL_OPEN = "UPDATE_SELL_OPEN";
export const UPDATE_FRACTIONAL_NFT_LIST = "UPDATE_FRACTIONAL_NFT_LIST";
export const UPDATE_FRACTIONAL_NFT_BALANCE = "UPDATE_FRACTIONAL_NFT_BALANCE";
export const UPDATE_FRACTIONAL_NFT_OWNERS = "UPDATE_FRACTIONAL_NFT_OWNERS";
export const TRANSACTION_ID = "TRANSACTION_ID";