export const TRANSFER_DIALOGUE = 'TRANSFER_DIALOGUE';
export const SELL_DIALOGUE = 'SELL_DIALOGUE';
export const FRACTIONAL_DIALOGUE = 'FRACTIONAL_DIALOGUE';
export const SEND_FRACTIONAL_DIALOGUE = 'SEND_FRACTIONAL_DIALOGUE';
export const LEND_DIALOGUE = 'LEND_DIALOGUE';