export const TRANSFER_DIALOGUE = 'TRANSFER_DIALOGUE';
export const SELL_DIALOGUE = 'SELL_DIALOGUE';
export const FRACTINAL_DIALOGUE = 'FRACTINAL_DIALOGUE';
export const LEND_DIALOGUE = 'LEND_DIALOGUE';